# Copyright © 2023 KubeCub & Xinwei Xiong(cubxxw). All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.


github: [cubxxw]
liberapay: "xiongxinwei/donate"
paypal: ["paypal.me/cubxxw", paypal.me]
custom: ["https://www.paypal.me/cubxxw", nsddd.top]