# Copyright © 2024 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: 'Code Language Detector'
description: 'Detects specified languages in comments within code files.'
inputs:
  go-version:
    description: 'The version of Go to use for running the detector.'
    required: true
    default: '1.20'
  detector-version:
    description: 'The version of the Comment Language Detector to install.'
    required: false
    default: 'latest'
  config-path:
    description: 'Path to the configuration file for the detector.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install Comment Language Detector
      run: go install github.com/kubecub/comment-lang-detector/cmd/cld@${{ inputs.detector-version }}
      shell: bash

    - name: Run Comment Language Detector
      run: cld
      shell: bash

branding:
  icon: 'search'
  color: 'blue'