# Copyright © 2024 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: "grype"

on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:

jobs:
  scan-source:
    name: scan-source
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
    - uses: anchore/scan-action@v3
      with:
        path: "."
        fail-build: true