# Copyright © 2023 KubeCub open source community. All rights reserved.
# Licensed under the MIT License (the "License");
# you may not use this file except in compliance with the License.

name: Comment Lang Detector Release Version

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu \
            libbtrfs-dev libgpgme-dev libdevmapper-dev \
            qemu-user-static binfmt-support

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.BOT_GITHUB_TOKEN }}

      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release --clean

        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
